### ISSUE TITLE
Role chooser

### ISSUE THREAD

**Issue by sebastienserre** [Pierre-Lannoy/wp-mailarchiver#1]
Hello and many thanks for this wonderful plugin.

It should be great to have in the settings a role chooser to allow other roles than "administrator" to use it.

In my example, I'm on a WooCommerce store, and the "Shop Manager" is testing WooCommerce emails.

See you

**Comment by Pierre-Lannoy** [comment]
Hi @sebastienserre !

Initially this was done like that for privacy reasons: mails (in production env.) are Personal Correspondence for some jurisdictions or PII for some other and, as such, must not be exposed to users who are not data controller / processor.

Nevertheless, your suggestion is a good one when testing/debugging, and I will try to find a way to achieve this.

Could you tell me: is your use-case about a production server or on dev/staging environment?

**Comment by sebastienserre** [comment]
I understand.
My use-case is a dev/staging environment for Polylang.pro
We need to test email without really sending them to our customers.

**Comment by Pierre-Lannoy** [comment]
That makes sense, thanks for the precision.
The next version of MailArchiver will provide such a feature based on `WP_ENVIRONMENT_TYPE` environment variable / constant introduced in WordPress 5.5.
Many thanks for the suggestion :)

**Comment by Pierre-Lannoy** [comment]
New feature released in [2.2.0](https://github.com/Pierre-Lannoy/wp-mailarchiver/releases/tag/2.2.0).
