### ISSUE TITLE
Resend Failed Emails

### ISSUE THREAD

**Issue by admsa** [Pierre-Lannoy/wp-mailarchiver#3]
Hello,

Thank you for this awesome plugin. I think it would be great to have a feature to resend failed emails. For example, failed emails due to authentication issues.

**Comment by Pierre-Lannoy** [comment]
Hello @admsa !
That's a very good suggestion.
I think it will be very tricky because there's many cases (many plugin to send mails, many transports, etc.)... Let me see how (and if) it is feasible 😄
